### ISSUE TITLE
Setup dev Postgres

### ISSUE THREAD

**Issue by JakeTrevor** [JARP-Inc/galactos#10]
We need to setup a local postgres server for dev purposes; SQLite has some compatibility issues which mean for best results we should use postgres directly.

**Comment by JakeTrevor** [comment]
Prisma has a good guide here:
[setting up a local postgresSQL database (on windows)](https://www.prisma.io/dataguide/postgresql/setting-up-a-local-postgresql-database#setting-up-postgresql-on-windows)

Alas, we will all need to do this individually

**Comment by RoryMcDermid** [comment]
Completed by Jake, Petros and Ash
